#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Disable bash history
unset HISTFILE

# Aliases
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

# PS1
PS1="\[\e[38;5;47m\]\u\[\e[38;5;156m\]@\[\e[38;5;227m\]\h \[\e[38;5;231m\]\w \[\033[0m\]$ "
